name: Quality assurance

on:
  push:
    branches:
      - master
      - develop
      - ga-*
  pull_request:

jobs:
  qa:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.event.repository.full_name
    runs-on: ubuntu-latest   
    steps:
      # Актуализация
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # https://github.com/marketplace/actions/sonarcloud-scan
          fetch-depth: 0
          
      # Установка JDK    
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Анализ в sonarcloud.io
      - name: Analyze with SonarCloud
        run: ./gradlew check sonarqube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     